# Generated by Django 3.2.4 on 2021-06-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_auto_20210623_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='title',
            field=models.CharField(max_length=100, verbose_name='título'),
        ),
    ]
