# Generated by Django 3.2.4 on 2021-06-24 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('call', '0007_remove_call_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
    ]
